import type { DetectionRule } from "@/lib/rules/types";

export const defaultDetectionRules: DetectionRule[] = [
  {
    id: "timeout",
    templateRuleId: "RULE_KEY_003",
    name: "Timeout",
    description: "Detect timeout related errors.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "timeout|timed out|read timed out|sockettimeoutexception",
    flags: "i",
    errorType: "timeout",
    subTags: ["timeout"],
    riskLevel: "high",
  },
  {
    id: "connection-refused",
    templateRuleId: "RULE_KEY_004",
    name: "Connection Refused",
    description: "Detect service or port refusal errors.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "connection refused|connectexception|refused to connect",
    flags: "i",
    errorType: "network_error",
    subTags: ["connection_refused", "db_or_service_call"],
    riskLevel: "high",
  },
  {
    id: "http-5xx",
    templateRuleId: "RULE_REG_001",
    name: "HTTP 5xx",
    description:
      "Detect explicit 5xx HTTP status lines without matching unrelated numbers such as stack frame line numbers or timeouts.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern:
      "(?:\\bhttp(?:\\/\\d(?:\\.\\d)?)?\\b[^\\r\\n]{0,24}\\b5\\d\\d\\b|\\bstatus(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bresponse(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bcode\\s*[=:]\\s*5\\d\\d\\b|\\b(?:bad gateway|service unavailable|gateway timeout)\\b)",
    flags: "i",
    errorType: "service_error",
    subTags: ["http_5xx", "server_error"],
    riskLevel: "high",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "http-403",
    templateRuleId: "RULE_REG_002",
    name: "HTTP 403",
    description: "Detect 403 forbidden events.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\b403\\b|forbidden",
    flags: "i",
    errorType: "permission_error",
    subTags: ["http_4xx", "http_403", "client_error"],
    riskLevel: "medium",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "permission-denied",
    templateRuleId: "RULE_KEY_005",
    name: "Permission Denied",
    description: "Detect permission related failures.",
    ruleCategory: "detection",
    matchType: "keyword",
    pattern: "permission denied",
    errorType: "permission_error",
    subTags: ["permission"],
    riskLevel: "medium",
  },
  {
    id: "application-auth-exception",
    templateRuleId: "RULE_REG_005",
    name: "Application Auth Exception",
    description: "Detect framework auth and CSRF rejection exceptions.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "accessdeniedexception|invalidcsrftokenexception|requestrejectedexception|csrfexception|permissiondenied",
    flags: "i",
    errorType: "permission_error",
    subTags: ["auth", "csrf", "access_control"],
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "resource-exhaustion",
    templateRuleId: "RULE_REG_006",
    name: "Resource Exhaustion",
    description: "Detect memory/disk/inode exhaustion signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "out of memory|oom-killer|no space left on device|inode usage at 100%|disk full|resource temporarily unavailable",
    flags: "i",
    errorType: "resource_exhaustion",
    subTags: ["oom", "disk", "inode", "resource"],
    riskLevel: "high",
    sourceTypes: ["system", "application", "custom", "postgres"],
  },
  {
    id: "database-auth-failure",
    templateRuleId: "RULE_REG_007",
    name: "Database Auth Failure",
    description: "Detect database authentication and pg_hba failures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "password authentication failed|no pg_hba\\.conf entry",
    flags: "i",
    errorType: "database_error",
    subTags: ["db_auth", "pg_hba"],
    riskLevel: "high",
    sourceTypes: ["postgres", "application", "custom"],
  },
  {
    id: "ssh-crypto-auth-failure",
    templateRuleId: "RULE_REG_008",
    name: "SSH Crypto/Auth Failure",
    description: "Detect SSH login failures and crypto integrity errors.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "user login failed|error in libcrypto|corrupted mac on input",
    flags: "i",
    errorType: "permission_error",
    subTags: ["ssh", "auth_failure", "crypto"],
    riskLevel: "high",
    sourceTypes: ["system", "application", "custom"],
  },
  {
    id: "dns-zone-transfer-failure",
    templateRuleId: "RULE_REG_009",
    name: "DNS Zone Transfer Failure",
    description: "Detect DNS AXFR/zone transfer failures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "zone transfer failed|denied axfr|non-authoritative zone",
    flags: "i",
    errorType: "network_error",
    subTags: ["dns", "axfr", "zone_transfer"],
    riskLevel: "low",
    sourceTypes: ["system", "custom"],
  },
  {
    id: "template-engine-error",
    templateRuleId: "RULE_REG_010",
    name: "Template Engine Error",
    description: "Detect template engine parse/init exceptions.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "parseerrorexception|templateinitexception|velocityexception",
    flags: "i",
    errorType: "service_error",
    subTags: ["template", "render", "runtime"],
    riskLevel: "low",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "sql-syntax-or-injection",
    templateRuleId: "RULE_REG_011",
    name: "SQL Syntax Or Injection Pattern",
    description: "Detect SQL syntax errors and injection-like signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "sqlsyntaxerrorexception|quoted string not properly terminated|unclosed quotation mark|union\\s+select",
    flags: "i",
    errorType: "database_error",
    subTags: ["sql_syntax", "sql_injection"],
    riskLevel: "high",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "external-process-exec-error",
    templateRuleId: "RULE_REG_012",
    name: "External Process Exec Error",
    description: "Detect external process execution failures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "node:child_process|cannot run program|processbuilder|child_process exec failed|spawn\\s+.*\\s+enoent",
    flags: "i",
    errorType: "service_error",
    subTags: ["process_exec", "runtime"],
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "generic-exception",
    templateRuleId: "RULE_KEY_006",
    name: "Exception",
    description: "Detect exception headers, cause lines, or traceback markers.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "exception|traceback|^caused by:",
    flags: "i",
    errorType: "unknown_error",
    subTags: ["exception", "runtime"],
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "generic-error",
    templateRuleId: "RULE_KEY_001",
    name: "Generic Error",
    description: "Detect generic error and failed signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\berror\\b|\\bfailed\\b|\\bfailure\\b",
    flags: "i",
    errorType: "unknown_error",
    subTags: ["error", "generic", "failed"],
    riskLevel: "medium",
    sourceTypes: ["application", "custom", "system", "postgres", "nginx"],
  },
  {
    id: "database-error",
    templateRuleId: "RULE_REG_004",
    name: "Database Error",
    description: "Detect common database failure signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "fatal|deadlock|remaining connection slots|too many connections",
    flags: "i",
    errorType: "database_error",
    subTags: ["db_error_code", "deadlock", "too_many_connections"],
    riskLevel: "high",
    sourceTypes: ["postgres", "application", "custom"],
  },
  {
    id: "fatal-error",
    templateRuleId: "RULE_KEY_008",
    name: "Fatal Error",
    description: "Detect fatal severity lines.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\bfatal\\b|\\bpanic\\b",
    flags: "i",
    errorType: "service_error",
    subTags: ["fatal", "panic"],
    riskLevel: "high",
  },
];
